networks:
  red-lab:
    external: true

services:
  spa-landing:
    build: .
    container_name: spa-landing
    networks:
      - red-lab
    ports:
      - "127.0.0.1:8090:80"
    restart: unless-stopped